### ISSUE TITLE
Invalid request

### ISSUE THREAD

**Issue by hiitsdan** [Warped2713/Discord-GitLab-Webhook#14]
When i try to test the request from gitlab, the bot says that the request is invalid? https://media.dans.website/oXxRiewYLB.png

**Comment by 23nd** [comment]
@hiitsdan Where did you put your webhook token? "Invalid" is only printed to the console if it failed to match the request's token to your webhook's token.

The webhook token can be found in your Discord app by creating or editing a webhook.
Once you have it copied, you should put it in 2 places:
1. The "Secret Token" field in **GitLab Settings > Integrations**
2. Either one of these two options:
  a. `webhook.token` in **require/config.json**, or
  b. in your local environment variables:
```
echo $DGW_WEBHOOK_TOKEN
export DGW_WEBHOOK_TOKEN=MySecretWebhookToken
echo $DGW_WEBHOOK_TOKEN
```

**Comment by 23nd** [comment]
Might be worth mentioning that the token is the last part of the Discord webhook's URL: `https://discordapp.com/api/webhooks/0000000000000/`**WebhookToken**` `

**Comment by hiitsdan** [comment]
my config looks like this

`{

  "bot": {
    "name": "GitLab Webhook Bot",
    "id": "572482975527206912",
    "token": "NTcyNDgyOTc1NTI3MjA2OTEy.XMc8WQ.iF8iH-1dGJFowa1tdIAzl5_2ULY",
    "prefix": ">",
    "debug_channel_id": "559167639822532608",
    "master_user_id": "169516316124905473"
  },

  "webhook": {
    "name": "Gitlab",
        "icon_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/GitLab_Logo.svg/1108px-GitLab_Logo.svg.png",
    "id": "568113160503164961",
    "token": "O8fMjz-WZ4MwCZJydl0wZ66Rhzj3C55PR0_T8KGL6edBDuVYNLFpIl7DV_MSj9Wd_mMC",
    "server": {
      "address": "localhost",
      "port": "8000"
    },
    "gitlab_url": "https://gitlab.com",
    "gitlab_access_token": "AgD6Aur-2C9XMpJSuweg",
    "DGW_WEBHOOK_TOKEN": ""
  }

}`

**Comment by hiitsdan** [comment]
Okay, I've figured it out. Thanks for your help!
